// Generated by CoffeeScript 2.5.1
(function() {
  var fs, tmpFolder;

  fs = require('fs');

  tmpFolder = function(dir) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir);
      return true;
    }
    return false;
  };

  module.exports = tmpFolder;

}).call(this);
