// Generated by CoffeeScript 2.5.1
(function() {
  var getFolderNameYYMMNNN, moment;

  moment = require('moment');

  getFolderNameYYMMNNN = function() {
    return moment().format('YYYYMM').toString();
  };

  module.exports = getFolderNameYYMMNNN;

}).call(this);
