// Generated by CoffeeScript 2.5.1
(function() {
  var cntFile, ls;

  ls = require('ls');

  exports.cntFolder = cntFile = function(file_name) {
    var file, files, i, len;
    files = ls('./' + file_name + '*', 'dir');
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      console.log(file);
    }
    return files.length;
  };

}).call(this);
